<<<<<<< HEAD
version: '3.9'

services:
  hardhat:
    build: .
    # O "command" abaixo é a única adição.
    # Ele sobrescreve o CMD do Dockerfile para garantir que o nó
    # Hardhat seja acessível de fora do contêiner.
    command: npx hardhat node --hostname 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8545:8545"
=======
version: '3.8'

services:
  geth_node:
    image: ethereum/client-go:v1.13.15
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - ./geth_config:/root/geth_config
      - ./geth_data:/root/.ethereum/node_data
    entrypoint: /bin/sh
    command: -c /root/geth_config/scripts/start_geth.sh
>>>>>>> b22cec106ccd5462efbe31c439795a75e686cbb9
